### ISSUE TITLE
Not full result returned for a small query

### ISSUE THREAD

**Issue by ibalashov** [GoogleCloudPlatform/google-cloud-datastore#123]
After investigating log files it looks like one of the datastore queries returned fewer rows than was expected (2 instead of 6 to be precise). The query was a simple _Cursor_-less, _Limit_-less entity query with a filter.

Is there a possibility that this scenario could have actually happened? Should we always use cursors and check if no more data was fetched, even if resulting dataset is small?

P.S. This might be better suited for SO, however, if someone interested I could provide necessary details of the query.

**Comment by pcostell** [comment]
Depending on the server constraints on your query Cloud Datastore may always choose to not return the full result set. You should always depend on the `RunQueryResponse`s `more_results` field to determine if another lookup is necessary (in particular, you will need to use cursors to fetch the remaining data if `more_results == NOT_FINISHED`). Note that the Cloud Datastore client libraries (gcloud-* and App Engine libraries) handle the batching for you.

Usually this happens if your query is a [merge join](https://cloud.google.com/appengine/articles/indexselection#Improved_Query_Planner) (multiple equality filters and no composite index for the query). In this case, your operations [scale with the size of the smallest set of results that match a single filter](https://cloud.google.com/appengine/articles/indexselection#Performance), which can explain the Cloud Datastore backends decided to return only a small number of results.

**Comment by ibalashov** [comment]
Unfortunately, this happened without merge and using Java client library (i.e. as you said _more_results_ check should have happened underneath in _com.google.cloud.datastore.QueryResultsImpl#QueryResultsImpl_)

Query part extracted:
```
val q = Query.entityQueryBuilder().kind("MyEntity").build
datastore.run(q, ReadOption.eventualConsistency)
```
I'll watch the logs if this comes up again, still assuming that this query cannot produce partial results.

**Comment by pcostell** [comment]
When you say "fewer rows than was expected", how do you know how many to expect? If you have committed these entities recently, this looks like [Eventual Consistency](https://cloud.google.com/datastore/docs/articles/balancing-strong-and-eventual-consistency-with-google-cloud-datastore).

**Comment by ibalashov** [comment]
Yes, you are absolute right about eventual consistency. However, I would not be surprised to see, say, 1K records out of 2K in couple of secs after insert. But, getting 2 out of 6 after ~ 40 seconds? Anyway, thanks for the suggestion, eventual consistency totally slipped my mind. Maybe datastore is not a good fit for this task.

**Comment by ibalashov** [comment]
Just for the record, this came up again.
2016-05-25 01:34:11 – 5 records added to datastore
2016-05-25 01:34:24 – 4 records appeared in result

**Comment by pcostell** [comment]
When you're designing your code to work with Cloud Datastore, you need to prepare for eventually consistent results. Any time you need results to be strongly consistent you have to either use parent entities and ancestor queries or do strongly consistent `Lookup` calls to retrieve your data.
