### ISSUE TITLE
Unexpected exception when transactions conflict

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/google-cloud-datastore#139]
Hi guys,

I am adding integration tests to gcloud-java's datastore module. When I run this code:
```Java
datastore.add(ENTITY1);
Transaction transaction = datastore.newTransaction();
transaction.get(KEY2);
transaction.update(Entity.builder(ENTITY1).clear().set("from", "transaction").build());
// update during the transaction
datastore.update(Entity.builder(ENTITY1).clear().set("from", "datastore").build());
transaction.commit();
```
I get different exceptions if I am running against the emulator (`v1.2.0`) or the actual service (`v1`).
* **Emulator**:
`com.google.datastore.v1.client.DatastoreException: too much contention on these datastore entities. please try again., code=ABORTED`
* **Actual Service**:
`com.google.datastore.v1.client.DatastoreException: transaction closed, code=INVALID_ARGUMENT`

Do you have any idea why this is happening? I believe the correct error should be `ABORTED`, right?

**Comment by eddavisson** [comment]
The two errors have slightly different meanings.

`too much contention on these datastore entities` means one of the entity groups in the transaction changed after it was first read or modified.

`transaction closed` means a request contained a transaction that was already closed (e.g. because it was already committed, rolled back, or closed by the server because some earlier transactional operation failed).

Couple of questions to try to narrow this down:

- Are these errors both coming from the `transaction.commit()` call?
- Do the errors happen every time?
- Are any of these operations asynchronous?

**Comment by mziccard** [comment]
> The two errors have slightly different meanings.

I am aware, this is the reason I am asking :)

In order:
- Yes, exceptions are thrown by `transaction.commit()`
- Yes, I tried >10 times and always got the same errors
- No

**Comment by eddavisson** [comment]
Are `KEY2` and `ENTITY1` in the same entity group? The call to `transaction.update()` shouldn't send an RPC to the server at all (all of the mutations happen in `commit()`).

**Comment by mziccard** [comment]
> The call to transaction.update() shouldn't send an RPC

In fact it doesn't.

> Are KEY2 and ENTITY1 in the same entity group?

`ENTITY1` is the parent of `KEY2`

**Comment by eddavisson** [comment]
Got it. So that at least explains why there's an error at all (`ABORTED` is the expected error).

I tried adding an analogous test to our internal tests. It's working with the protocol buffers directly:

```
Key parentKey = datastoreResource.newV1Key("Parent");
Key childKey = datastoreResource.newV1Key(parentKey, "Child");
Entity parentEntity = Entity.newBuilder()
    .setKey(parentKey)
    .build();
datastore.commit(makeUpsert(parentEntity));

ByteString txn = datastore.beginTransaction();
// lookup() causes the transaction to track the entity group
datastore.lookup(txn, childKey);

// update during the transaction
Entity.Builder parentEntityD = parentEntity.toBuilder();
parentEntityD.getMutableProperties()
    .put("from", Value.newBuilder().setStringValue("datastore").build());
datastore.commit(makeUpsert(parentEntityD.build()));

Entity.Builder parentEntityT = parentEntity.toBuilder();
parentEntityT.getMutableProperties()
    .put("from", Value.newBuilder().setStringValue("transaction").build());
datastore.commit(txn, makeUpsert(parentEntityT.build()));
```

This test fails with the `ABORTED` error against both prod and the emulator (as expected).

It seems like the requests being made by `gcloud-java` are not what we expect. Is it possible to add logging to see what actual RPCs are being sent to the service?

**Comment by mziccard** [comment]
Oh god now I see what is happening.

We added `ABORTED` to our retryable exceptions. This does not happen against the emulator because there we run with a no-retry policy. So sorry to have wasted your time on this.

I wonder wether we should really automatically retry `ABORTED` transactions, or let the user handle the error.
