### ISSUE TITLE
Google cloud datastore slow. >1 sec / query

### ISSUE THREAD

**Issue by nojvek** [GoogleCloudPlatform/google-cloud-datastore#190]
We've been getting consistent greater than 1 second on average calls from gcds. Not sure why its ridiculously slow.

We are using it from python.

```
from google.cloud import datastore

client = datastore.Client('foo', 'bar')
client.query(
  kind='Blah',
  filters=(
      ('name', '=', 'yolo'),
  ),
  order=('timestamp',)
)

print(list(query.fetch()))
```

Very simple call but consistently very slow.

Related to #154, but I see that is already closed.

**Comment by wsh** [comment]
Hey there--this repo is for the low-level google-cloud-datastore client (which has package google.datastore). You're using [google-cloud-python](https://github.com/GoogleCloudPlatform/google-cloud-python), which is great (!), but a separate repo. Please file an issue there and we can look into this.

**Comment by zappan** [comment]
@wsh I'm having the same issue of DB insert being slow, ran once in 10 minutes (data arriving from some IoT device) - using Node, not Python, and there is the similar topic https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/154 where you also redirect people to the higher level datastore client, while it's obvious that the issue is present across client libs.

Also, your project structure is something known to you internally, for us outside users, it's not that well known, and as I see no cross-links, look like people fell out of your funnel in reporting these issues in those places. I hope you understand that different points of view are heavily different here, yours from the inside, and ours from the outside.

It would be highly appreciated if you could actually do that extra step for your users, and open the issues in the places where you find it necessary to be opened, and link this and the above-mentioned issues from those, and cross-link to them here for tracking, if you still think they belong in client libs (although it seems the issue is somewhere else, like people already mentioned, it's happening in different environments). 

Thanks for understanding, and I hope you'll do some steps in the right direction with this. Cheers
