### ISSUE TITLE
Datastore class leaks http connections, eventually runs out so all requests block & timeout

### ISSUE THREAD

**Issue by faizalkassamalisc** [GoogleCloudPlatform/google-cloud-datastore#91]
If a Datastore object is created with DatastoreOptions that include HttpTransport whose HttpClient has set a org.apache.http.impl.conn.PoolingHttpClientConnectionManager, RemoteRpc soon exhausts all available connections.  Subsequent requests to the Datastore object block until the timeout expires and then fail.

The issue I believe is com.google.api.services.datastore.client.RemoteRpc does not call org.apache.http.conn.HttpClientConnectionManager.releaseConnection() to return a connection back to the connection manager and make it reusable by other consumers.

**Comment by pcostell** [comment]
I don't think RemoteRpc can close the connection because `call(...)` returns an `InputStream` from the response which would get cleared if we disconnected.

Instead, I think `Datastore` may need to explicitly close the `InputStream`. Per [`HttpResponse#getContent()`](https://developers.google.com/api-client-library/java/google-http-java-client/reference/1.19.0/com/google/api/client/http/HttpResponse#getContent()), the underlying connection should get disconnected if we close the content.

**Comment by crahen** [comment]
Did you guys test this client or are we the first to attempt actually using it?

**Comment by faizalkassamalisc** [comment]
Thanks for the quick response @pcostell.  Seems like a high severity bug.  Is there a plan to fix the Datastore class?

**Comment by eddavisson** [comment]
Fixed in 1.0.0-beta.1.
https://github.com/GoogleCloudPlatform/google-cloud-datastore/blob/master/java/RELEASE_NOTES.md#v1beta3-100-beta1
