### ISSUE TITLE
Opaque exception for mismatched Datastore projects

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-datastore#98]
See https://github.com/GoogleCloudPlatform/gcloud-python/issues/1693

**Comment by pcostell** [comment]
@bendemaree This should now be fixed --

storage.googleapis.com/gcd/tools/gcd-v1beta3-1.0.1.zip

**Comment by bendemaree** [comment]
@pcostell Excellent, thank you!

Based on the Cloud Datastore [emulator guides](https://cloud.google.com/datastore/docs/tools/datastore-emulator) I had inferred that directly using GCD is unsupported since it ships with `gcloud`; I based that partly on being unable to find a `v1beta3` download link like the one you gave here. Is that the case, and if so, any guess on when it will be updated in `gcloud`?

**Comment by pcostell** [comment]
@bendemaree -- We've transitioned our docs mostly to `gcloud` since it has a nicer update/install story than a zip download. However, `gcloud beta emulators datastore` is just backed by `gcd.sh`, so it isn't unsupported just hidden.

I don't have an update yet on when it will be in `gcloud`.
